datadog_metric:
  description: Send a gauge metric to datadog, via dogstatsd
  fields:
    metric:
      required: true
      example: "sensor.thermometer"
      selector:
        text:
    value:
      required: true
      example: 42.0
      selector:
        template:
    tags:
      required: false
      advanced: true
      selector:
        template:
